# Generated by Django 5.2.2 on 2025-06-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
