# Generated by Django 5.2.2 on 2025-06-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cartitem_order_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
