# Generated by Django 5.2.2 on 2025-06-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_order_product_remove_product_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
